# Generated by Django 4.2.26 on 2025-11-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('due_date', models.DateField(help_text='Due date (YYYY-MM-DD)')),
                ('due_time', models.TimeField(help_text='Due time (HH:MM)')),
                ('estimated_hours', models.FloatField(help_text='Estimated hours to complete (must be > 0)', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('importance', models.IntegerField(help_text='Importance rating (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs this task depends on')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('program_manager', 'Program Manager')], default='developer', help_text='User role for strategy selection', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or description for the task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
